// AUTO-GENERATED by server/scripts/export-manifest.ts — DO NOT EDIT BY HAND.
// Mirror of server/src/modules/composition/manifest.ts for the KORT frontend.
// Regenerate: `npm run composition:manifest` in server/.

import type { CompositionManifest } from './manifest-types';

export const MANIFEST_VERSION = "a3a17d73415a";

export const COMPOSITION_MANIFEST: CompositionManifest = {
  "version": "a3a17d73415a",
  "sections": [
    {
      "id": "leads",
      "label": "Лиды",
      "removable": true,
      "planTier": "basic"
    },
    {
      "id": "customers",
      "label": "Клиенты",
      "removable": true,
      "planTier": "basic"
    },
    {
      "id": "tasks",
      "label": "Задачи",
      "removable": true,
      "planTier": "advanced"
    },
    {
      "id": "sales",
      "label": "Продажи",
      "removable": false,
      "planTier": "basic"
    },
    {
      "id": "warehouse",
      "label": "Склад",
      "removable": true,
      "planTier": "basic"
    },
    {
      "id": "production",
      "label": "Производство",
      "removable": true,
      "planTier": "advanced"
    },
    {
      "id": "logistics",
      "label": "Логистика",
      "removable": true,
      "planTier": "advanced"
    },
    {
      "id": "products",
      "label": "Продукты",
      "removable": true,
      "planTier": "basic"
    },
    {
      "id": "finance",
      "label": "Финансы",
      "removable": true,
      "planTier": "advanced"
    },
    {
      "id": "reports",
      "label": "Отчёты",
      "removable": true,
      "planTier": "advanced"
    },
    {
      "id": "documents",
      "label": "Документы",
      "removable": true,
      "planTier": "advanced"
    }
  ],
  "surfaces": [
    {
      "id": "sidebar",
      "label": "Боковая навигация",
      "blocks": [
        {
          "id": "leads",
          "label": "Лиды",
          "surface": "sidebar",
          "group": "CRM",
          "defaultOrder": 0,
          "removable": true,
          "planTier": "basic",
          "permission": null
        },
        {
          "id": "sales",
          "label": "Продажи",
          "surface": "sidebar",
          "group": "CRM",
          "defaultOrder": 1,
          "removable": false,
          "planTier": "basic",
          "permission": null
        },
        {
          "id": "customers",
          "label": "Клиенты",
          "surface": "sidebar",
          "group": "CRM",
          "defaultOrder": 2,
          "removable": true,
          "planTier": "basic",
          "permission": null
        },
        {
          "id": "tasks",
          "label": "Задачи",
          "surface": "sidebar",
          "group": "CRM",
          "defaultOrder": 3,
          "removable": true,
          "planTier": "advanced",
          "permission": null
        },
        {
          "id": "warehouse",
          "label": "Склад",
          "surface": "sidebar",
          "group": "Операции",
          "defaultOrder": 4,
          "removable": true,
          "planTier": "basic",
          "permission": null
        },
        {
          "id": "production",
          "label": "Производство",
          "surface": "sidebar",
          "group": "Операции",
          "defaultOrder": 5,
          "removable": true,
          "planTier": "advanced",
          "permission": null
        },
        {
          "id": "logistics",
          "label": "Логистика",
          "surface": "sidebar",
          "group": "Операции",
          "defaultOrder": 6,
          "removable": true,
          "planTier": "advanced",
          "permission": null
        },
        {
          "id": "products",
          "label": "Продукты",
          "surface": "sidebar",
          "group": "Операции",
          "defaultOrder": 7,
          "removable": true,
          "planTier": "basic",
          "permission": null
        },
        {
          "id": "finance",
          "label": "Финансы",
          "surface": "sidebar",
          "group": "Операции",
          "defaultOrder": 8,
          "removable": true,
          "planTier": "advanced",
          "permission": null
        },
        {
          "id": "reports",
          "label": "Отчёты",
          "surface": "sidebar",
          "group": "Аналитика",
          "defaultOrder": 9,
          "removable": true,
          "planTier": "advanced",
          "permission": null
        },
        {
          "id": "documents",
          "label": "Документы",
          "surface": "sidebar",
          "group": "Аналитика",
          "defaultOrder": 10,
          "removable": true,
          "planTier": "advanced",
          "permission": null
        }
      ]
    },
    {
      "id": "new-order",
      "label": "Форма нового заказа",
      "blocks": [
        {
          "id": "client",
          "label": "Клиент",
          "surface": "new-order",
          "group": null,
          "defaultOrder": 0,
          "removable": false,
          "planTier": null,
          "permission": null
        },
        {
          "id": "line-items",
          "label": "Позиции заказа",
          "surface": "new-order",
          "group": null,
          "defaultOrder": 1,
          "removable": false,
          "planTier": null,
          "permission": null
        },
        {
          "id": "dates",
          "label": "Сроки и приоритет",
          "surface": "new-order",
          "group": null,
          "defaultOrder": 2,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "payment",
          "label": "Оплата",
          "surface": "new-order",
          "group": null,
          "defaultOrder": 3,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "notes",
          "label": "Примечания",
          "surface": "new-order",
          "group": null,
          "defaultOrder": 4,
          "removable": true,
          "planTier": null,
          "permission": null
        }
      ]
    },
    {
      "id": "warehouse",
      "label": "Раздел «Склад»",
      "blocks": [
        {
          "id": "stats-bar",
          "label": "Сводка по складу",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 0,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "twin-panel",
          "label": "Цифровой двойник",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 1,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "site-bootstrap",
          "label": "Управление площадками",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 2,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "structure-bootstrap",
          "label": "Зоны и ячейки",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 3,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "receipts",
          "label": "Приёмка",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 4,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "transfers",
          "label": "Перемещения",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 5,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "reservations",
          "label": "Резервы",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 6,
          "removable": true,
          "planTier": null,
          "permission": null
        },
        {
          "id": "documents",
          "label": "Документы склада",
          "surface": "warehouse",
          "group": null,
          "defaultOrder": 7,
          "removable": true,
          "planTier": null,
          "permission": null
        }
      ]
    }
  ]
};
