// ЧАСТЬ X — generates the KORT frontend's manifest mirror from the backend
// source of truth. Run: `npm run composition:manifest` (in server/).
//
// The backend owns server/src/modules/composition/manifest.ts; the frontend
// must not import from server/. This script serialises the manifest into
// src/shared/composition/manifest.generated.ts. Parity tests fail CI on drift.

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { COMPOSITION_MANIFEST, MANIFEST_VERSION } from '../src/modules/composition/manifest.js';

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '../../src/shared/composition/manifest.generated.ts');

const file = `// AUTO-GENERATED by server/scripts/export-manifest.ts — DO NOT EDIT BY HAND.
// Mirror of server/src/modules/composition/manifest.ts for the KORT frontend.
// Regenerate: \`npm run composition:manifest\` in server/.

import type { CompositionManifest } from './manifest-types';

export const MANIFEST_VERSION = ${JSON.stringify(MANIFEST_VERSION)};

export const COMPOSITION_MANIFEST: CompositionManifest = ${JSON.stringify(
  COMPOSITION_MANIFEST,
  null,
  2,
)};
`;

writeFileSync(target, file, 'utf8');
console.log(`composition manifest exported → ${target} (version ${MANIFEST_VERSION})`);
